name: Execute notebook

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: yaananth/run-notebook@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "/notebooks/Fig2.ipynb"
          isReport: False
          poll: True
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: output
          path: ${{ RUNNER.temp }}/nb-runner
        env:
          RUNNER: ${{ toJson(runner) }}